FROM builder-base

RUN cd /tmp

WORKDIR /tmp

RUN git clone https://git.openwrt.org/openwrt/openwrt.git

WORKDIR /tmp/openwrt

RUN git checkout $VERSION

RUN ./scripts/feeds update -a
RUN ./scripts/feeds update -i
