FROM debian:buster

# Reduce chance of error during deps installation
ENV DEBIAN_FRONTEND="noninteractive"

# Update system
RUN apt update -y ; apt upgrade -y

# Install deps from https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu
RUN apt install -y build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils zlib1g-dev

RUN apt install -y unzip wget rsync libpam liblzma
